# Wilson's Morning Wake Up Playlist Generator, Modeling and Learning

The following steps will be executed:

* Upload your data to S3.
* Define a benchmark and candidate models and training scripts
* Train models and deploy.
* Evaluate deployed estimator.

## Load Data to S3

In [1]:
import pandas as pd
import boto3
import sagemaker

In [2]:
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

In [3]:
!ls -la data

total 456
drwxrwxr-x 2 ec2-user ec2-user   4096 Mar 18 23:10 .
drwxrwxr-x 8 ec2-user ec2-user   4096 Mar 19 04:06 ..
-rw-rw-r-- 1 ec2-user ec2-user  28467 Mar  4 23:01 test.csv
-rw-rw-r-- 1 ec2-user ec2-user 165699 Mar 19 00:12 train.csv
-rw-rw-r-- 1 ec2-user ec2-user  90194 Mar 19 00:12 wmw.csv
-rw-rw-r-- 1 ec2-user ec2-user 166951 Mar 18 23:35 wmw_tracks.csv


## Upload your training data to S3

In [4]:
# should be the name of directory you created to save your features data
data_dir = 'data'

# set prefix, a descriptive name for a directory  
prefix = 'sagemaker/wmw_estimator'

# upload all data to S3
input_data = sagemaker_session.upload_data(path=data_dir, bucket=bucket, key_prefix=prefix)

---

# Modeling

It's time to define and train the models!

---

## Complete a training script 

To implement a custom estimator, I need to complete a `train.py` script. 

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model

To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section


In [5]:
# Directory of train.py
!pygmentize model/train.py

Error: cannot read infile: [Errno 2] No such file or directory: 'model/train.py'


---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `source_sklearn` OR `source_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## Define PyTorch estimators

In [6]:
# Build sequences and targets
def create_playlist_sequences(input_data):
    input_playlists = []
    
    for i in input_data['volume'].unique():
        temp_vol = input_data[input_data['volume'] == i]
        X = temp_vol.iloc[:, 2:10].values
        y = temp_vol.iloc[:, 10:].values
        input_playlists.append((X, y))
        
    return input_playlists

In [7]:
from unittest.mock import MagicMock, patch

def _print_success_message():
    print('Tests Passed!')

def test_playlist_sequences(input_playlists):
    
    track_features = [-2.39099487, -2.63509459, -0.27732204,  0.92969533, -0.48983686,-1.15691947,  1.08569029, -1.20454903,  2.09618458, -5.37044178, 0.23380331]
    
    track_features_len = 11
    target_features_len = 8
    
    # check shape and equality of first track
    assert len(input_playlists[0][0][0]) == len(track_features), \
        'Number of features in input_playlist features does not match expected number of ' + str(len(track_features))    
    
    # check shape of input and output arrays
    assert input_playlists[0][0].shape[1]==track_features_len, \
        'input_features should have as many columns as selected features, got: {}'.format(train_x.shape[1])
    assert input_playlists[0][1].shape[1]==target_features_len, \
        'target_features should have as many columns as selected features, got: {}'.format(train_x.shape[1])
    
    #TODO: Add more tests
    
    _print_success_message()

### Test run of benchmark and candidate models and train components
Here I will see if the configurations I have set work accordingly with no errors. Once it runs smoothly, I will instantiate an estimator using the Sagemaker API.

In [8]:
import os
import torch
import torch.utils.data

train_data = pd.read_csv(os.path.join(data_dir, "train.csv"))

# Gather sequences and targets
processed_data = create_playlist_sequences(train_data)

In [9]:
# Training function for LSTM
def train_lstm(model, train_loader, epochs, criterion, optimizer, device):
    """
    This is the training method that is called by the PyTorch training script of the LSTM model. The parameters
    passed are as follows:
    model        - The PyTorch model that we wish to train.
    train_loader - The PyTorch DataLoader that should be used during training.
    epochs       - The total number of epochs to train for.
    criterion    - The loss function used for training. 
    optimizer    - The optimizer to use during training.
    device       - Where the model and data should be loaded (gpu or cpu).
    """
    
    # training loop is provided
    for epoch in range(1, epochs + 1):
        
        model.train() # Make sure that the model is in training mode.

        total_loss = 0

        for batch in train_loader:
            
            # get data
            batch_x, batch_y = batch
            
            # 
            batch_x = torch.from_numpy(batch_x).float().squeeze()
            batch_y = torch.from_numpy(batch_y).float()

            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            
            model.hidden_cell = (torch.zeros(1, 1, model.hidden_layer_dim),
                torch.zeros(1, 1, model.hidden_layer_dim))

            # get predictions from model
            y_pred = model(batch_x)
            
            # perform backprop
            loss = criterion(y_pred, batch_y)
            loss.backward()
            optimizer.step()
            
            total_loss += loss.data.item()
            
        if epoch%25 == 1:
            print("Epoch: {}, Loss: {}".format(epoch, total_loss / len(train_loader)))

In [11]:
import torch.optim as optim
from model.LSTM_Estimator import LSTMEstimator

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = LSTMEstimator(8, 30, 1, 8)
optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = torch.nn.L1Loss()

train_lstm(model, processed_data, 100, loss_fn, optimizer, device)

Epoch: 1, Loss: 0.672984648395229
Epoch: 26, Loss: 0.5712427996300362
Epoch: 51, Loss: 0.5238120588096412
Epoch: 76, Loss: 0.4796866669848159


In [12]:
%env SPOTIFY_EMAIL=gillaw06@gmail.com

env: SPOTIFY_EMAIL=gillaw06@gmail.com


In [13]:
%env SPOTIFY_ID=ce1d1ca394724265951a48a0deea6d01

env: SPOTIFY_ID=ce1d1ca394724265951a48a0deea6d01


In [14]:
%env SPOTIFY_SECRET=3ce5bb4c8c18423f9e8b3f12db963e31

env: SPOTIFY_SECRET=3ce5bb4c8c18423f9e8b3f12db963e31


In [15]:
!pip install spotipy

fastai 1.0.60 requires nvidia-ml-py3, which is not installed.
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [16]:
# Spotify API
import spotipy
import spotipy.util as util

# Defaults
import os
import sys

# Spotify for developers client auth variables
username = os.environ['SPOTIFY_EMAIL']
spotify_id = os.environ['SPOTIFY_ID']
spotify_secret = os.environ['SPOTIFY_SECRET']

# Set API scope
scope='playlist-read-private'

# Get auth token
token = util.prompt_for_user_token(username, 
                                   scope,
                                   client_id=spotify_id,
                                   client_secret=spotify_secret,
                                   redirect_uri='http://localhost/')

In [17]:
from spotipy.oauth2 import SpotifyClientCredentials

In [18]:

#Authenticate
sp = spotipy.Spotify(
    client_credentials_manager = SpotifyClientCredentials(
        client_id=spotify_id,
        client_secret=spotify_secret
    )
)

In [19]:
# Read in WMW tracks to date for recommendations
track_data = pd.read_csv(os.path.join(data_dir, "wmw_tracks.csv"))

track_data.head()

volume  position                                   track_name  \
0      38         1                             Finding It There   
1      38         2                                  Light Forms   
2      38         3                                       C-Side   
3      38         4               Didn't I (Dave Allison Rework)   
4      38         5  Woman Of The Ghetto - Akshin Alizadeh Remix   

    artist_name  danceability   energy  key  loudness  mode  speechiness  ...  \
0      Goldmund         0.187  0.00257    1   -37.134     1       0.0427  ...   
1         Rohne         0.671  0.54500   10   -12.848     0       0.0393  ...   
2    Khruangbin         0.688  0.77900   11   -10.129     0       0.0579  ...   
3       Darondo         0.539  0.70500    0    -6.729     1       0.0527  ...   
4  Marlena Shaw         0.707  0.57300    7    -8.403     0       0.0276  ...   

   liveness  valence    tempo            type                      id  \
0    0.0915   0.0374  123.707  audio_features  6CnPCuUcM3A5PMP4gUy0vw   
1    0.1180   0.2840  133.036  audio_features  6MkUPsz5hYeneo0a9H0VT8   
2    0.3490   0.9380   94.073  audio_features  6GvAM8oyVApQHGMgpBt8yl   
3    0.1330   0.6850  186.033  audio_features  1owjOeZt1BdYWW6T8fIAEe   
4    0.0858   0.1890  100.006  audio_features  2h8cQH7zhUWrynZi2MKhhC   

                                    uri  \
0  spotify:track:6CnPCuUcM3A5PMP4gUy0vw   
1  spotify:track:6MkUPsz5hYeneo0a9H0VT8   
2  spotify:track:6GvAM8oyVApQHGMgpBt8yl   
3  spotify:track:1owjOeZt1BdYWW6T8fIAEe   
4  spotify:track:2h8cQH7zhUWrynZi2MKhhC   

                                          track_href  \
0  https://api.spotify.com/v1/tracks/6CnPCuUcM3A5...   
1  https://api.spotify.com/v1/tracks/6MkUPsz5hYen...   
2  https://api.spotify.com/v1/tracks/6GvAM8oyVApQ...   
3  https://api.spotify.com/v1/tracks/1owjOeZt1BdY...   
4  https://api.spotify.com/v1/tracks/2h8cQH7zhUWr...   

                                        analysis_url duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/6CnP...      220120   
1  https://api.spotify.com/v1/audio-analysis/6MkU...      265870   
2  https://api.spotify.com/v1/audio-analysis/6GvA...      283407   
3  https://api.spotify.com/v1/audio-analysis/1owj...      328000   
4  https://api.spotify.com/v1/audio-analysis/2h8c...      302467   

  time_signature  
0              5  
1              4  
2              4  
3              4  
4              4  

[5 rows x 22 columns]

In [25]:
from tqdm.notebook import tqdm
from sklearn.externals import joblib

feature_list =  ['danceability','energy', 'loudness', 'speechiness', 'acousticness',
                 'instrumentalness', 'liveness', 'valence']

#'mode','key','tempo'

std_scaler = joblib.load('standard_features.pkl')

class Playlist():
    def __init__(self):
        self.name = "Wilson's Morning Wake Up Vol. Test"
        self.intro_songs = []
        self.search_results = []
        self.recommended_track_ids = pd.DataFrame() #list of track ids straight from spotify
        self.trax = [] #all tracks as dict
        self.df = None #this is where the data goes
        self.playlist = None
        
       
        # DO EVERYTHING
        self.get_recommendations() # Grab recommendations based on full WMW catalog
        self.prep_features() # Prepare features using StandardScaler
#         self.get_predictions() # Generate features for each track position for new WMW
        
        
    def get_recommendations(self):
        print('Getting Recommendations...')
        
        # Iterate full catalog of WMW songs
        for _, row in tqdm(track_data[track_data['volume'] == 38].iterrows(), total=track_data[track_data['volume'] == 38].shape[0]):
            song_search = row['track_name'].partition('-')[0] + ' ' + row['artist_name']
            try:
        
                # Query Spotify to get track metadata
                song_res = sp.search(song_search, limit=1)['tracks']['items'][0]

                self.search_results.append({
                    'id': song_res['id'],
                    'artists': [i['name'] for i in song_res['artists']],
                    'name': song_res['name']
                })
                
                # Gather recommendations for each of the past WMW tracks
                results = sp.recommendations(seed_tracks = [song_res['id']], limit=10)

                for r in results['tracks']:
                    track={}
                    track['id'] = r['id']
                    track['artists'] = [i['name'] for i in r['artists']],
                    track['name'] = r['name']
                    track_features = sp.audio_features(r['id'])[0]
                    track.update(track_features)
                    final_track = pd.DataFrame(track, index=[0])
                    self.recommended_track_ids = self.recommended_track_ids.append(final_track, ignore_index=True)
                    
            except:
                print("Song not searchable")
        
        return self.recommended_track_ids
    
    
    def prep_features(self):
        self.recommended_track_ids[feature_list] = std_scaler.transform(self.recommended_track_ids[feature_list])
            
    
    def generate_playlist_features(model, intro_tracks, predict_len=15):
        hidden = model.init_hidden()
        
        # extracts features from intro tracks
        intro_input = text_to_tensor()
        
        # predicted playlist
        predicted = intro_tracks
        
        # build up hidden state
        for p in range(len(intro_tracks) - 1):
            _, hidden = model(intro_input[p], hidden)
        inp = intro_input[-1]
        
        for p in range(predict_len):
            output, hidden = model(inp, hidden)
            


In [21]:
pl = Playlist()

Getting Recommendations...


/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:63: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


ValueError: operands could not be broadcast together with shapes (150,11) (8,) (150,11) 

In [ ]:
pl.recommended_track_ids

In [29]:
import random

recommended = pd.DataFrame()

# Iterate full catalog of WMW songs
for _, row in tqdm(track_data[track_data['volume'] == random.randint(1, 38)].iterrows(), total=track_data[track_data['volume'] == 38].shape[0]):
    song_search = row['track_name'].partition('-')[0] + ' ' + row['artist_name']
    try:

        # Query Spotify to get track metadata
        song_res = sp.search(song_search, limit=1)['tracks']['items'][0]

        # Gather recommendations for each of the past WMW tracks
        results = sp.recommendations(seed_tracks = [song_res['id']], limit=10)

        for r in results['tracks']:
            track={}
            track['id'] = r['id']
            track['artists'] = [i['name'] for i in r['artists']],
            track['name'] = r['name']
            track_features = sp.audio_features(r['id'])[0]
            track.update(track_features)
            final_track = pd.DataFrame(track, index=[0])
            recommended = recommended.append(final_track, ignore_index=True)

    except:
        print("Song not searchable")
        
        

Song not searchable



In [30]:
recommended[feature_list] = std_scaler.transform(recommended[feature_list])


In [31]:
recommended[feature_list].head()

danceability    energy  loudness  speechiness  acousticness  \
0     -1.270634 -1.953245 -1.698487    -0.413963      2.101379   
1     -2.283823 -1.430230 -0.480783    -0.382700      1.758053   
2     -2.267029 -2.509883 -3.175392    -0.391632      2.149991   
3     -1.158680 -2.319823 -1.377730    -0.041034      2.128723   
4     -1.656877 -1.934566 -1.145537    -0.313473      2.098340   

   instrumentalness  liveness   valence  
0          0.880142 -0.370022 -1.045094  
1          0.824983 -0.309774 -0.814932  
2          0.813371 -0.759378 -1.079364  
3          0.778533 -0.528928 -0.836087  
4          0.830789 -0.339898 -0.857242

In [35]:
# song = [ 0.0609,  1.0491,  0.5765, -0.3122, -0.6526,  0.0296, -0.7938,  0.0199]

from scipy.spatial.distance import cdist

import numpy as np

# np.argmin(cdist([song], recommended[feature_list]))

In [154]:
recommended.iloc[142]

id                                             4Zwo8D1koSzLJCYd5NlX81
artists                                                       [Tycho]
name                                                     Outer Sunset
danceability                                                 0.526236
energy                                                       0.545087
key                                                                 8
loudness                                                   -0.0348222
mode                                                                1
speechiness                                                 -0.235315
acousticness                                                 0.691617
instrumentalness                                             0.824983
liveness                                                    -0.473198
valence                                                       1.59245
tempo                                                          96.994
type                

In [36]:
from tqdm.notebook import tqdm
from sklearn.externals import joblib

feature_list =  ['danceability','energy', 'loudness', 'speechiness', 'acousticness',
                 'instrumentalness', 'liveness', 'valence']

std_scaler = joblib.load('standard_features.pkl')

def predict_playlist(model, initial_songs=[], predict_len=15):
    global recommended
    intro_tracks = pd.DataFrame() #list of track ids straight from spotify
    
    model.eval()
    
    # Iterate full catalog of WMW songs
    for song in tqdm(initial_songs, total=len(initial_songs)):
                
        song_search = song
                
        try:
            
            # Query Spotify to get track metadata
            song_res = sp.search(song_search, limit=1)['tracks']['items'][0]
            
            track = {
                'id': song_res['id'],
                'artists': [i['name'] for i in song_res['artists']],
                'name': song_res['name']
            }
            
            track_features = sp.audio_features(track['id'])[0]
            
            track.update(track_features)
            
            final_track = pd.DataFrame(track, index=[0])
            
            intro_tracks = intro_tracks.append(final_track, ignore_index=True)
                
        except:
            print("Song not searchable")

    intro_tracks[feature_list] = std_scaler.transform(intro_tracks[feature_list])
            
    predicted = intro_tracks

    inp = torch.FloatTensor(intro_tracks[feature_list].values)
    
    print("Intro", inp)

    sample = recommended.copy()

    for p in range(predict_len):
        output = model(inp).detach().numpy()
        next_song_id = np.argmin(cdist(output, sample[feature_list]))
        next_song = sample.iloc[next_song_id].copy()
        inp = torch.FloatTensor([next_song[feature_list]])
        print("New song", next_song['artists'], next_song['name'])
        predicted = predicted.append(next_song, ignore_index=True)
        sample = sample.drop([next_song_id], axis=0).reset_index(drop=True)
        
    return predicted

In [39]:
def harmonic_match(key, mode):
    
    key = key
    mode = mode
        
    # Harmonic Mixing Wheel: Pitch Class 
    # 1A - A flat minor: 8
    # 1B - B major: 11
    # 2A - E flat minor: 3
    # 2B - F-sharp major: 6
    # 3A - B-flat minor: 10
    # 3B - D-flat major: 1
    # 4A - F minor: 5
    # 4B - A-flat major: 8
    # 5A - C minor: 0
    # 5B - E-flat major: 3
    # 6A - G minor: 7
    # 6B - B-flat major: 10
    # 7A - D minor: 2
    # 7B - F major: 5
    # 8A - A minor: 9
    # 8B - C major: 0
    # 9A - E minor: 4
    # 9B - G major: 7
    # 10A - B minor: 11
    # 10B - D major: 2
    # 11A - F sharp minor: 6
    # 11B - A major: 9
    # 12A - D flat minor: 1
    # 12B - E major: 4

    
#     harmonic_wheel_to_pitch = {8:0, 3:1, 10:2, 
#                                5:3, 0:4, 7:5, 
#                                2:6, 9:7, 4:8,
#                                11:9,6:10, 1:11}
    
        
    pitch_to_harmonic_wheel = {0: [8, 11] 1: [3, 6], 2: [10, 1], 
                               3: [5, 8], 4: [0, 3], 5: [7, 10], 
                               6: [2, 5], 7: [9, 0], 8: [4, 7],
                               9: [11, 2],10: [6, 9],11: [1, 4]}
    
    pitch_to_harmonic_wheel[key] = 
    
    # Harmonic Wheel: 
    # http://www.harmonic-mixing.com/Images/camelotHarmonicMixing.jpg
    harmonic_wheel = [[0 , 1 , 2, 3, 4, 0],
                      [1 , 1 , 2, 3, 4, 4],
                      [12, 12, 0, 0, 5, 5],
                      [11, 11, 0, 0, 6, 6],
                      [10, 10, 9, 8, 7, 7],
                      [0 , 10, 9, 8, 7, 0]]
    
    harmonic_wheel = np.array(harmonic_wheel)
    
    # Extract values and keys
    dv = np.array(list(pitch_to_harmonic_wheel.values()))
    dk = np.array(list(pitch_to_harmonic_wheel.keys()))

    # Harmonic octave
    harmonic_octave = dv[np.where(dk == key)][0][mode]
    print("Harmonic octave: ", harmonic_octave)
    
    rows = np.where(harmonic_octave == harmonic_wheel)[0]
    cols = np.where(harmonic_octave == harmonic_wheel)[1]

    zip(rows, cols):
        
    
    

In [41]:
pitch_to_harmonic_wheel = {0: [8, 11], 1: [3, 6],  2: [10, 1], 
                           3: [5, 8],  4: [0, 3],  5: [7, 10], 
                           6: [2, 5],  7: [9, 0],  8: [4, 7],
                           9: [11, 2], 10: [6, 9], 11: [1, 4]}

In [71]:
harmonic_wheel = [[1, 0 , 2, 3, 0, 4],
                  [0 , 1 , 2, 3, 4, 0],
                  [12, 12, 0, 0, 5, 5],
                  [11, 11, 0, 0, 6, 6],
                  [0, 10, 9, 8, 7, 0],
                  [10 , 0, 9, 8, 0, 7]]

In [43]:
# Extract values and keys
dv = np.array(list(pitch_to_harmonic_wheel.values()))
dk = np.array(list(pitch_to_harmonic_wheel.keys()))

In [51]:
dv

array([[ 8, 11],
       [ 3,  6],
       [10,  1],
       [ 5,  8],
       [ 0,  3],
       [ 7, 10],
       [ 2,  5],
       [ 9,  0],
       [ 4,  7],
       [11,  2],
       [ 6,  9],
       [ 1,  4]])

In [52]:
dk

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
# Key = 8, Mode = 0
key = 8
mode = 0

# Harmonic octave
harmonic_octave = dv[np.where(dk == key)][0][mode]
print("Harmonic octave: ", harmonic_octave)

Harmonic octave:  4


In [102]:
harmonic_wheel = np.array(harmonic_wheel)

In [106]:
harmonic_wheel

array([[ 1,  0,  2,  3,  0,  4],
       [ 0,  1,  2,  3,  4,  0],
       [12, 12,  0,  0,  5,  5],
       [11, 11,  0,  0,  6,  6],
       [ 0, 10,  9,  8,  7,  0],
       [10,  0,  9,  8,  0,  7]])

In [119]:
x, y = 1, 4

print(harmonic_wheel[x-1:x+1, y-1:y+2])

[[3 0 4]
 [3 4 0]]


In [134]:
# row, column
x, y = 2, 4
print("Row:", x + 1, "Column:", y + 1)
print()
print("Neighbours:\n", harmonic_wheel[x-1:x+2, y-1:y+2])
print()
print("Uniques: \n", set(harmonic_wheel[x-1:x+2, y-1:y+2].ravel()))
print()

Row: 3 Column: 5

Neighbours:
 [[3 4 0]
 [0 5 5]
 [0 6 6]]

Uniques: 
 {0, 3, 4, 5, 6}



In [82]:
np.where(harmonic_octave == harmonic_wheel)

(array([0, 1]), array([5, 4]))

In [139]:
np.where(harmonic_octave == harmonic_wheel).ravel()

AttributeError: 'tuple' object has no attribute 'ravel'

In [143]:
rows = np.where(harmonic_octave == harmonic_wheel)[0]
cols = np.where(harmonic_octave == harmonic_wheel)[1]

a, b = zip(rows, cols)

In [144]:
a,b 

((0, 5), (1, 4))

In [ ]:
from unittest.mock import MagicMock, patch

def _print_success_message():
    print('Tests Passed!')

def test_harmonic_mixing(song):
    
    truth_octaves = []
    
    next_octaves = harmonic_match(8, 1)
    
    # check shape and equality of first track
    assert len(truth_octaves) == len(next_octaves), \
        'Number of octaves incorrect, should get: ' + str(len(truth_octaves))    
    
    # check shape of input and output arrays
    assert input_playlists[0][0].shape[1]==track_features_len, \
        'input_features should have as many columns as selected features, got: {}'.format(train_x.shape[1])
    assert input_playlists[0][1].shape[1]==target_features_len, \
        'target_features should have as many columns as selected features, got: {}'.format(train_x.shape[1])
    
    #TODO: Add more tests
    
    _print_success_message()

In [110]:
import numpy as np

initial_songs = ['luke howard portrait gallery']

predict_playlist(model, initial_songs=initial_songs, predict_len=14)


Intro tensor([[-1.7968, -2.6588, -4.1506, -0.4095,  2.1287,  0.7989, -0.4152, -0.9601]])
New song ['Zola Blood'] Good Love
New song ['Oliver Schories'] Brizzle
New song ['Tycho'] Coastal Brake
New song ['DJ Koze'] Pick Up
New song ['Maribou State'] Rituals
New song ['Vessels'] Elliptic
New song ['Caribou'] Sun
New song ['Equador', 'Sieren'] Avalon - Sieren Remix
New song ['Com Truise'] Silicon Tare
New song ['Tall Ships'] Day by Day
New song ['Kidnap'] Vehl
New song ['Chon'] Book
New song ['DAVID AUGUST'] Epikur - Original
New song ['Enrico Sangiuliano'] Astral Projection


id               artists                   name  \
0   3oRuCzqdduzZ2CBhAtv8zO           Luke Howard       Portrait Gallery   
1   0vbbQvmRs38P27DCSctZ7L          [Zola Blood]              Good Love   
2   3GPYUPEP8O4cMn7mLA9RX1     [Oliver Schories]                Brizzle   
3   0dE9ro91KUtV5Xi7bDPy6b               [Tycho]          Coastal Brake   
4   5YzBL3vkQnp3JbeDRRSbSQ             [DJ Koze]                Pick Up   
5   0UCU2uiUBfToI9EDdrS6aJ       [Maribou State]                Rituals   
6   3qQ6Y9vTezy0CZAi9QObvj             [Vessels]               Elliptic   
7   0c7V10APHbimDgQppV8dFz             [Caribou]                    Sun   
8   1Oym7AEESwzeCjaFvFT4OC     [Equador, Sieren]  Avalon - Sieren Remix   
9   05vajmV6LbINFD5fGBS9my          [Com Truise]           Silicon Tare   
10  2lnplRF8NCYfdyKqaJNCG0          [Tall Ships]             Day by Day   
11  6TecGli3dA4NMIdH6C9K4m              [Kidnap]                   Vehl   
12  0zCbXOPent461dbCEBRQwM                [Chon]                   Book   
13  5XxFY11r0YA6Xoyh1O9WsR        [DAVID AUGUST]      Epikur - Original   
14  32nw9Qc5rYjsPWGLy14Yh5  [Enrico Sangiuliano]      Astral Projection   

    danceability    energy  key  loudness  mode  speechiness  acousticness  \
0      -1.796820 -2.658849    1 -4.150644     1    -0.409497      2.128723   
1       0.246349 -0.019956    4  0.449872     0    -0.527852      0.077884   
2       0.873295 -0.118022    0  0.229195     1     0.269368     -0.705384   
3      -0.134296  1.096121    9  0.292425     1    -0.282210     -0.338360   
4       0.503845  0.106128    5  0.421189     1     0.146547     -0.870026   
5       0.515040 -0.136701   10  0.428307     0    -0.105794     -0.588714   
6      -0.610103  0.404994   10 -0.114593     0    -0.509987     -0.597829   
7       0.380695  1.152159    1  0.755136     1    -0.389399     -0.747920   
8      -0.352607  0.787916    6  1.001775     0    -0.554649     -0.819624   
9      -0.554125  0.848623    9  0.914467     0    -0.469791     -0.450777   
10     -0.643689  1.259564    9  0.930589     1    -0.266578     -0.870042   
11     -0.632493  0.820604    5  1.094736     0    -0.427362     -0.761896   
12     -0.083916  1.077442    6  0.895833     1    -0.601544     -0.798660   
13     -0.369400  0.092119    1 -0.027075     1    -0.543483     -0.832992   
14      0.985249  0.745888    6  0.549114     0     0.115283     -0.814763   

    instrumentalness  liveness   valence    tempo            type  \
0           0.798855 -0.415209 -0.960053  127.536  audio_features   
1          -0.098201 -0.339898  0.073558   95.005  audio_features   
2           0.909173 -0.513866 -0.087216  123.015  audio_features   
3           1.007878 -0.362491  0.272411  120.008  audio_features   
4           0.494030 -0.436296  0.830891  124.912  audio_features   
5          -0.002399 -0.362491  0.272411  121.012  audio_features   
6           0.795952 -0.211870 -0.070293  123.013  audio_features   
7           0.508546  0.119496  0.564344  127.983  audio_features   
8           0.505642 -0.423493 -0.925782  133.072  audio_features   
9           0.290813 -0.279650  0.289335  176.208  audio_features   
10          0.020826 -0.504828  0.115867  100.026  audio_features   
11         -0.562697 -0.515372 -0.523000  129.929  audio_features   
12          0.639185  0.021593  0.653193  114.990  audio_features   
13          0.793049  0.850009 -0.738776  117.989  audio_features   
14          0.897560 -0.347429  0.035480  124.981  audio_features   

                                     uri  \
0   spotify:track:3oRuCzqdduzZ2CBhAtv8zO   
1   spotify:track:0vbbQvmRs38P27DCSctZ7L   
2   spotify:track:3GPYUPEP8O4cMn7mLA9RX1   
3   spotify:track:0dE9ro91KUtV5Xi7bDPy6b   
4   spotify:track:5YzBL3vkQnp3JbeDRRSbSQ   
5   spotify:track:0UCU2uiUBfToI9EDdrS6aJ   
6   spotify:track:3qQ6Y9vTezy0CZAi9QObvj   
7   spotify:track:0c7V10APHbimDgQppV8dFz   
8   spotify:track:1Oym7AEESwzeCjaFvFT4OC   
9   spotify:track:05vajmV6LbI

In [11]:
# # Training function
# def train_rnn(model, train_loader, epochs, criterion, optimizer, device):
#     """
#     This is the training method that is called by the PyTorch training script. The parameters
#     passed are as follows:
#     model        - The PyTorch model that we wish to train.
#     train_loader - The PyTorch DataLoader that should be used during training.
#     epochs       - The total number of epochs to train for.
#     criterion    - The loss function used for training. 
#     optimizer    - The optimizer to use during training.
#     device       - Where the model and data should be loaded (gpu or cpu).
#     """
    
#     # training loop is provided
#     for epoch in range(1, epochs + 1):
#         model.train() # Make sure that the model is in training mode.

#         total_loss = 0
        
#         hidden = model.initHidden()

#         for batch in train_loader:
            
#             # get data
#             batch_x, batch_y = batch
            
#             # 
#             batch_x = torch.from_numpy(batch_x).float().squeeze()
#             batch_y = torch.from_numpy(batch_y).float()

#             batch_x = batch_x.to(device)
#             batch_y = batch_y.to(device)

#             optimizer.zero_grad()

#             y_pred = []
            
#             # get predictions
#             for x in batch_x:
#                 y, hidden = model(x, hidden)
#                 y_pred.append(y)
            
#             # perform backprop
#             loss = criterion(y_pred, batch_y)
#             loss.backward()
#             optimizer.step()
            
#             total_loss += loss.data.item()
            
#         if epoch%25 == 1:
#             print("Epoch: {}, Loss: {}".format(epoch, total_loss / len(train_loader)))

#TODO: Create working RNN Benchmark model

In [18]:
# import torch.optim as optim
# from model.RnnEstimator import RNNEstimator

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model = RNNEstimator(11, 30, 8)
# optimizer = optim.Adam(model.parameters(), lr=0.001)
# loss_fn = torch.nn.L1Loss()

# train_rnn(model, processed_data, 100, loss_fn, optimizer, device)

### Build and Train the PyTorch Model with Hyperparameter Tuning

In [15]:
# Estimator code
from sagemaker.pytorch import PyTorch
output_path = 's3://{}/{}'.format(bucket, prefix)

estimator = PyTorch(entry_point="LSTM_Train.py",
                    source_dir="model",
                    role=role,
                    framework_version='0.4.0',
                    train_instance_count=1,
                    output_path = output_path,
                    train_instance_type='ml.m4.xlarge',
                    hyperparameters={
                        'input_features': 11,
                        'hidden_dim': 12,
                        'output_dim': 8,
                        'epochs': 100
                    })

In [16]:
# Fit estimator
estimator.fit({'train': input_data})

2020-03-05 03:44:03 Starting - Starting the training job...
2020-03-05 03:44:04 Starting - Launching requested ML instances.........
2020-03-05 03:45:34 Starting - Preparing the instances for training.........
2020-03-05 03:47:17 Downloading - Downloading input data
2020-03-05 03:47:17 Training - Downloading the training image..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-03-05 03:47:37,157 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2020-03-05 03:47:37,160 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-03-05 03:47:37,172 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2020-03-05 03:47:37,176 sagemaker_pytorch_container.training INFO     Invoking user training script.
2020-03-05 03:47:37,390 sagemaker-containers INFO     Module LSTM_Train does not provide a setup.py. 
Generating setup.py
2020-03-05 0

In [17]:
%%time

# deploy your model to create a predictor
predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

-----------!CPU times: user 254 ms, sys: 15.1 ms, total: 270 ms
Wall time: 5min 32s


In [28]:
torch.Tensor(processed_data[0][0]).float()

tensor([[-2.3910e+00, -2.6351e+00, -2.7732e-01,  9.2970e-01, -4.8984e-01,
         -1.1569e+00,  1.0857e+00, -1.2045e+00,  2.0962e+00, -5.3704e+00,
          2.3380e-01],
        [ 2.9102e-01, -1.3109e-01, -3.5296e-01,  6.4590e-01, -2.8399e-01,
         -1.2541e-01, -9.2107e-01,  1.4323e+00,  6.8586e-01, -3.7562e-01,
          6.8282e-01],
        [ 3.8522e-01,  9.4912e-01,  6.0842e-02, -1.4610e+00,  1.5104e+00,
          2.6102e+00, -9.2107e-01,  1.7253e+00, -7.7038e-01,  1.8358e-01,
         -1.1925e+00],
        [-4.4044e-01,  6.0751e-01, -5.4846e-02, -1.4123e+00, -1.6747e-01,
          1.5519e+00,  1.0857e+00, -1.4975e+00, -8.6166e-01,  8.8285e-01,
          3.2336e+00],
        [ 4.9051e-01, -1.8348e-03, -6.1326e-01, -9.6511e-01, -5.3411e-01,
         -5.2279e-01, -9.2107e-01,  5.5335e-01, -8.1149e-01,  5.3856e-01,
         -9.0695e-01],
        [ 6.9554e-01,  1.2076e+00, -5.0396e-02,  8.1217e-01, -7.6404e-01,
         -7.5214e-02,  1.0857e+00, -3.2617e-02,  3.1377e-01,  1.0708e-0

In [31]:
preds = predictor.predict(torch.Tensor(processed_data[0][0]).float())

In [32]:
len(preds)

15

In [49]:
torch.Tensor(new_tracks[-1]).float()

tensor([-2.3910, -2.6351, -0.2773,  0.9297, -0.4898, -1.1569,  1.0857, -1.2045,
         2.0962, -5.3704,  0.2338])

In [57]:
fut_pred = processed_data[0][0][0]

[-2.3909948690196825,
 -2.635094590468726,
 -0.2773220412902482,
 0.9296953263811546,
 -0.4898368594156362,
 -1.1569194705342014,
 1.0856902892884872,
 -1.2045490262286025,
 2.0961845785776654,
 -5.370441776536932,
 0.23380331292868914]

In [62]:
# model.eval()

fut_pred = processed_data[0][0][0]

playlist_len = 15

new_tracks = [torch.Tensor(fut_pred).float()]

print(new_tracks[-1])


predictor.predict(new_tracks[-1])

# for i in range(playlist_len - len(fut_pred)):
#         print(i)
#         print(predictor.predict(new_tracks[-1].values))
#         break

tensor([-2.3910, -2.6351, -0.2773,  0.9297, -0.4898, -1.1569,  1.0857, -1.2045,
         2.0962, -5.3704,  0.2338])


ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
". See https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-pytorch-2020-03-05-03-44-02-776 in account 999752527953 for more information.